export const symbols = [
  { symbol: 'AAPL', quantity: 10, name: 'Apple Inc.' },
  { symbol: 'MSFT', quantity: 5, name: 'Microsoft Corporation' },
  { symbol: 'GOOGL', quantity: 3, name: 'Alphabet Inc.' },
  { symbol: 'AMZN', quantity: 2, name: 'Amazon.com Inc.' },
  { symbol: 'TSLA', quantity: 4, name: 'Tesla Inc.' },
  { symbol: 'META', quantity: 6, name: 'Meta Platforms Inc.' },
  { symbol: 'JNJ', quantity: 8, name: 'Johnson & Johnson' },
  { symbol: 'PFE', quantity: 7, name: 'Pfizer Inc.' },
  { symbol: 'WMT', quantity: 9, name: 'Walmart Inc.' },
  { symbol: 'KO', quantity: 7, name: 'Coca-Cola Co.' },
  { symbol: 'BA', quantity: 187, name: 'Boeing Co.' },
  { symbol: 'NOC', quantity: 190, name: 'Northrop Grumman Corp.' },
  { symbol: 'SPR', quantity: 197, name: 'Spirit AeroSystems Holdings Inc.' },
  { symbol: 'HXL', quantity: 199, name: 'Hexcel Corp.' },
  { symbol: 'V', quantity: 12, name: 'Visa Inc.' },
  { symbol: 'MA', quantity: 11, name: 'Mastercard Inc.' },
  { symbol: 'JPM', quantity: 15, name: 'JPMorgan Chase & Co.' },
  { symbol: 'GS', quantity: 10, name: 'Goldman Sachs Group Inc.' },
  { symbol: 'DIS', quantity: 8, name: 'The Walt Disney Company' },
  { symbol: 'NFLX', quantity: 6, name: 'Netflix Inc.' },
  { symbol: 'T', quantity: 20, name: 'AT&T Inc.' },
  { symbol: 'VZ', quantity: 18, name: 'Verizon Communications Inc.' },
  { symbol: 'CVX', quantity: 14, name: 'Chevron Corporation' },
  { symbol: 'XOM', quantity: 16, name: 'Exxon Mobil Corporation' },
  { symbol: 'BP', quantity: 12, name: 'BP plc' },
  { symbol: 'COP', quantity: 10, name: 'ConocoPhillips' },
  { symbol: 'PG', quantity: 9, name: 'Procter & Gamble Co.' },
  { symbol: 'CL', quantity: 8, name: 'Colgate-Palmolive Co.' },
  { symbol: 'PEP', quantity: 7, name: 'PepsiCo Inc.' },
  { symbol: 'MDLZ', quantity: 6, name: 'Mondelez International Inc.' },
  { symbol: 'UNH', quantity: 5, name: 'UnitedHealth Group Inc.' },
  { symbol: 'CVS', quantity: 7, name: 'CVS Health Corporation' },
  { symbol: 'ABT', quantity: 8, name: 'Abbott Laboratories' },
  { symbol: 'MRK', quantity: 9, name: 'Merck & Co. Inc.' },
  { symbol: 'BMY', quantity: 6, name: 'Bristol-Myers Squibb Company' },
  { symbol: 'LLY', quantity: 5, name: 'Eli Lilly and Company' },
  { symbol: 'HD', quantity: 10, name: 'The Home Depot Inc.' },
  { symbol: 'LOW', quantity: 8, name: "Lowe's Companies Inc." },
  { symbol: 'TGT', quantity: 7, name: 'Target Corporation' },
  { symbol: 'COST', quantity: 6, name: 'Costco Wholesale Corporation' },
  { symbol: 'SBUX', quantity: 5, name: 'Starbucks Corporation' },
  { symbol: 'MCD', quantity: 4, name: "McDonald's Corporation" },
  { symbol: 'YUM', quantity: 3, name: 'Yum! Brands Inc.' },
  { symbol: 'CMG', quantity: 2, name: 'Chipotle Mexican Grill Inc.' },
  { symbol: 'NKE', quantity: 5, name: 'Nike Inc.' },
  { symbol: 'UA', quantity: 4, name: 'Under Armour Inc.' },
  { symbol: 'LULU', quantity: 3, name: 'Lululemon Athletica Inc.' },
  { symbol: 'DECK', quantity: 2, name: 'Deckers Outdoor Corporation' },
  { symbol: 'UAA', quantity: 1, name: 'Under Armour Inc. Class A' },
];